### ISSUE TITLE
Border radius

### ISSUE THREAD

**Issue by supertiger1234** [04SeoHyun/electron-acrylic-window#1]
Is there anyway to add border radius? I tried `bored-radius: 4px` but it didnt seem to work.

Amazing job btw! 

Thanks.

**Comment by 04SeoHyun** [comment]
I'm sorry, but I don't think it's possible. This module uses the "SetWindowCompositionAttribute" API in Windows 10, which I understand is impossible to manipulate in detail, such as setting the curvature of a corner. If you know any other way to make the window acrylic effect, please let me know and I will reflect it in the update later. Thank you.

**Comment by tscpp** [comment]
https://github.com/microsoft/microsoft-ui-xaml/issues/1247#issuecomment-698266336

**Comment by Seo-Rii** [comment]
@tscpp This module is not currently using the WinUI. Also, WinUI is currently in beta and is not sure if it can be applied reliably to this module. If WinUI is officially released, we will reopen this issue.

**Comment by tscpp** [comment]
> SetWindowRgn (Which is what WindowChrome in WPF uses to set the CornerRadius) works! It clips not only the WPF Window but also to the "DesktopWindowXamlSource" xaml islands child window!

SetWindowRgn is a function included in the c++ Win32 API
