### ISSUE TITLE
keep getting this response 

### ISSUE THREAD

**Issue by ethugbaby** [04SeoHyun/electron-acrylic-window#2]
![image](https://user-images.githubusercontent.com/50474744/81458137-87d41d00-915e-11ea-9801-eec5bb42b1b4.png)

**Comment by ethugbaby** [comment]
im using the code from the example in the readme i am on windows 10, electron 8.2.5

**Comment by 04SeoHyun** [comment]
Sorry, there was a critical mistake on last release. 
It will fixed on 0.2.1.
Please wait a moment!

**Comment by 04SeoHyun** [comment]
The problem has been resolved on v0.2.1.
I'm sorry for the inconvenience.
